// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReqRegister.proto

package com.snail.message;

public final class ReqRegisterMsg {
  private ReqRegisterMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqRegisterOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 id = 1 [default = 100];
    /**
     * <code>optional int32 id = 1 [default = 100];</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1 [default = 100];</code>
     */
    int getId();

    // optional int32 user_id = 2;
    /**
     * <code>optional int32 user_id = 2;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int32 user_id = 2;</code>
     */
    int getUserId();

    // optional string user_name = 3;
    /**
     * <code>optional string user_name = 3;</code>
     */
    boolean hasUserName();
    /**
     * <code>optional string user_name = 3;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>optional string user_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // optional string pwd = 4;
    /**
     * <code>optional string pwd = 4;</code>
     */
    boolean hasPwd();
    /**
     * <code>optional string pwd = 4;</code>
     */
    java.lang.String getPwd();
    /**
     * <code>optional string pwd = 4;</code>
     */
    com.google.protobuf.ByteString
        getPwdBytes();

    // optional string email = 5;
    /**
     * <code>optional string email = 5;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 5;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 5;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // optional .myProto.ReqRegister.Sex sex = 6 [default = NONE];
    /**
     * <code>optional .myProto.ReqRegister.Sex sex = 6 [default = NONE];</code>
     */
    boolean hasSex();
    /**
     * <code>optional .myProto.ReqRegister.Sex sex = 6 [default = NONE];</code>
     */
    com.snail.message.ReqRegisterMsg.ReqRegister.Sex getSex();
  }
  /**
   * Protobuf type {@code myProto.ReqRegister}
   */
  public static final class ReqRegister extends
      com.google.protobuf.GeneratedMessage
      implements ReqRegisterOrBuilder {
    // Use ReqRegister.newBuilder() to construct.
    private ReqRegister(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqRegister(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqRegister defaultInstance;
    public static ReqRegister getDefaultInstance() {
      return defaultInstance;
    }

    public ReqRegister getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqRegister(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              userName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              pwd_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              email_ = input.readBytes();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.snail.message.ReqRegisterMsg.ReqRegister.Sex value = com.snail.message.ReqRegisterMsg.ReqRegister.Sex.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                sex_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.snail.message.ReqRegisterMsg.internal_static_myProto_ReqRegister_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.snail.message.ReqRegisterMsg.internal_static_myProto_ReqRegister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.snail.message.ReqRegisterMsg.ReqRegister.class, com.snail.message.ReqRegisterMsg.ReqRegister.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqRegister> PARSER =
        new com.google.protobuf.AbstractParser<ReqRegister>() {
      public ReqRegister parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqRegister(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqRegister> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code myProto.ReqRegister.Sex}
     */
    public enum Sex
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NONE = 0;</code>
       */
      NONE(0, 0),
      /**
       * <code>MALE = 1;</code>
       */
      MALE(1, 1),
      /**
       * <code>FEMALE = 2;</code>
       */
      FEMALE(2, 2),
      ;

      /**
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <code>MALE = 1;</code>
       */
      public static final int MALE_VALUE = 1;
      /**
       * <code>FEMALE = 2;</code>
       */
      public static final int FEMALE_VALUE = 2;


      public final int getNumber() { return value; }

      public static Sex valueOf(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return MALE;
          case 2: return FEMALE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Sex>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Sex>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
              public Sex findValueByNumber(int number) {
                return Sex.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.snail.message.ReqRegisterMsg.ReqRegister.getDescriptor().getEnumTypes().get(0);
      }

      private static final Sex[] VALUES = values();

      public static Sex valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Sex(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:myProto.ReqRegister.Sex)
    }

    private int bitField0_;
    // optional int32 id = 1 [default = 100];
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1 [default = 100];</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1 [default = 100];</code>
     */
    public int getId() {
      return id_;
    }

    // optional int32 user_id = 2;
    public static final int USER_ID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <code>optional int32 user_id = 2;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 user_id = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // optional string user_name = 3;
    public static final int USER_NAME_FIELD_NUMBER = 3;
    private java.lang.Object userName_;
    /**
     * <code>optional string user_name = 3;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string user_name = 3;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string user_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string pwd = 4;
    public static final int PWD_FIELD_NUMBER = 4;
    private java.lang.Object pwd_;
    /**
     * <code>optional string pwd = 4;</code>
     */
    public boolean hasPwd() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string pwd = 4;</code>
     */
    public java.lang.String getPwd() {
      java.lang.Object ref = pwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pwd = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPwdBytes() {
      java.lang.Object ref = pwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string email = 5;
    public static final int EMAIL_FIELD_NUMBER = 5;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 5;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string email = 5;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .myProto.ReqRegister.Sex sex = 6 [default = NONE];
    public static final int SEX_FIELD_NUMBER = 6;
    private com.snail.message.ReqRegisterMsg.ReqRegister.Sex sex_;
    /**
     * <code>optional .myProto.ReqRegister.Sex sex = 6 [default = NONE];</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .myProto.ReqRegister.Sex sex = 6 [default = NONE];</code>
     */
    public com.snail.message.ReqRegisterMsg.ReqRegister.Sex getSex() {
      return sex_;
    }

    private void initFields() {
      id_ = 100;
      userId_ = 0;
      userName_ = "";
      pwd_ = "";
      email_ = "";
      sex_ = com.snail.message.ReqRegisterMsg.ReqRegister.Sex.NONE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPwdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getEmailBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, sex_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPwdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getEmailBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, sex_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.snail.message.ReqRegisterMsg.ReqRegister parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.snail.message.ReqRegisterMsg.ReqRegister parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.snail.message.ReqRegisterMsg.ReqRegister parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.snail.message.ReqRegisterMsg.ReqRegister parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.snail.message.ReqRegisterMsg.ReqRegister parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.snail.message.ReqRegisterMsg.ReqRegister parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.snail.message.ReqRegisterMsg.ReqRegister parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.snail.message.ReqRegisterMsg.ReqRegister parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.snail.message.ReqRegisterMsg.ReqRegister parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.snail.message.ReqRegisterMsg.ReqRegister parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.snail.message.ReqRegisterMsg.ReqRegister prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code myProto.ReqRegister}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.snail.message.ReqRegisterMsg.ReqRegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.snail.message.ReqRegisterMsg.internal_static_myProto_ReqRegister_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.snail.message.ReqRegisterMsg.internal_static_myProto_ReqRegister_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.snail.message.ReqRegisterMsg.ReqRegister.class, com.snail.message.ReqRegisterMsg.ReqRegister.Builder.class);
      }

      // Construct using com.snail.message.ReqRegisterMsg.ReqRegister.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 100;
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        pwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        sex_ = com.snail.message.ReqRegisterMsg.ReqRegister.Sex.NONE;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.snail.message.ReqRegisterMsg.internal_static_myProto_ReqRegister_descriptor;
      }

      public com.snail.message.ReqRegisterMsg.ReqRegister getDefaultInstanceForType() {
        return com.snail.message.ReqRegisterMsg.ReqRegister.getDefaultInstance();
      }

      public com.snail.message.ReqRegisterMsg.ReqRegister build() {
        com.snail.message.ReqRegisterMsg.ReqRegister result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.snail.message.ReqRegisterMsg.ReqRegister buildPartial() {
        com.snail.message.ReqRegisterMsg.ReqRegister result = new com.snail.message.ReqRegisterMsg.ReqRegister(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pwd_ = pwd_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sex_ = sex_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.snail.message.ReqRegisterMsg.ReqRegister) {
          return mergeFrom((com.snail.message.ReqRegisterMsg.ReqRegister)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.snail.message.ReqRegisterMsg.ReqRegister other) {
        if (other == com.snail.message.ReqRegisterMsg.ReqRegister.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000004;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasPwd()) {
          bitField0_ |= 0x00000008;
          pwd_ = other.pwd_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000010;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.snail.message.ReqRegisterMsg.ReqRegister parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.snail.message.ReqRegisterMsg.ReqRegister) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 id = 1 [default = 100];
      private int id_ = 100;
      /**
       * <code>optional int32 id = 1 [default = 100];</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1 [default = 100];</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1 [default = 100];</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1 [default = 100];</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 100;
        onChanged();
        return this;
      }

      // optional int32 user_id = 2;
      private int userId_ ;
      /**
       * <code>optional int32 user_id = 2;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 user_id = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional int32 user_id = 2;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 user_id = 2;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0;
        onChanged();
        return this;
      }

      // optional string user_name = 3;
      private java.lang.Object userName_ = "";
      /**
       * <code>optional string user_name = 3;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string user_name = 3;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_name = 3;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_name = 3;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_name = 3;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userName_ = value;
        onChanged();
        return this;
      }

      // optional string pwd = 4;
      private java.lang.Object pwd_ = "";
      /**
       * <code>optional string pwd = 4;</code>
       */
      public boolean hasPwd() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string pwd = 4;</code>
       */
      public java.lang.String getPwd() {
        java.lang.Object ref = pwd_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pwd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pwd = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPwdBytes() {
        java.lang.Object ref = pwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pwd = 4;</code>
       */
      public Builder setPwd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        pwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pwd = 4;</code>
       */
      public Builder clearPwd() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pwd_ = getDefaultInstance().getPwd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pwd = 4;</code>
       */
      public Builder setPwdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        pwd_ = value;
        onChanged();
        return this;
      }

      // optional string email = 5;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 5;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string email = 5;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 5;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 5;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 5;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000010);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 5;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        email_ = value;
        onChanged();
        return this;
      }

      // optional .myProto.ReqRegister.Sex sex = 6 [default = NONE];
      private com.snail.message.ReqRegisterMsg.ReqRegister.Sex sex_ = com.snail.message.ReqRegisterMsg.ReqRegister.Sex.NONE;
      /**
       * <code>optional .myProto.ReqRegister.Sex sex = 6 [default = NONE];</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .myProto.ReqRegister.Sex sex = 6 [default = NONE];</code>
       */
      public com.snail.message.ReqRegisterMsg.ReqRegister.Sex getSex() {
        return sex_;
      }
      /**
       * <code>optional .myProto.ReqRegister.Sex sex = 6 [default = NONE];</code>
       */
      public Builder setSex(com.snail.message.ReqRegisterMsg.ReqRegister.Sex value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .myProto.ReqRegister.Sex sex = 6 [default = NONE];</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sex_ = com.snail.message.ReqRegisterMsg.ReqRegister.Sex.NONE;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:myProto.ReqRegister)
    }

    static {
      defaultInstance = new ReqRegister(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:myProto.ReqRegister)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_myProto_ReqRegister_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_myProto_ReqRegister_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ReqRegister.proto\022\007myProto\"\262\001\n\013ReqRegi" +
      "ster\022\017\n\002id\030\001 \001(\005:\003100\022\017\n\007user_id\030\002 \001(\005\022\021" +
      "\n\tuser_name\030\003 \001(\t\022\013\n\003pwd\030\004 \001(\t\022\r\n\005email\030" +
      "\005 \001(\t\022+\n\003sex\030\006 \001(\0162\030.myProto.ReqRegister" +
      ".Sex:\004NONE\"%\n\003Sex\022\010\n\004NONE\020\000\022\010\n\004MALE\020\001\022\n\n" +
      "\006FEMALE\020\002B#\n\021com.snail.messageB\016ReqRegis" +
      "terMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_myProto_ReqRegister_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_myProto_ReqRegister_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_myProto_ReqRegister_descriptor,
              new java.lang.String[] { "Id", "UserId", "UserName", "Pwd", "Email", "Sex", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
